<?php

use Drupal\Core\Form\FormStateInterface;
  
  function customblock_form_node_appointments_form_alter(&$form, FormStateInterface $form_state, $form_id)
   {dpm($form);
         $form['title']['#prefix']='<div class="anil col-sm-12 col-xs-12 col-xl-12 col-md-12 form-control form-group">';
        
         $form['title']['#suffix']='</div>';
         //$form['actions']['#prefix']='<div class="anil col-sm-12 col-xs-12 col-xl-12 col-md-12">';
         $form['actions']['#prefix'] = '<div class="anil col-sm-12 col-xs-12 col-xl-12 col-md-12" >';
         $form['actions']['#suffix'] = '</div>';
         $form['#attached']['library'][] = 'customblock/global-css';
         
         
         return $form;
   
    
    }    
    


